version: '2'
services:
  phabricator:
    restart: always
    ports:
    - "8443:443"
    - "8080:80"
    - "2222:22"
    volumes:
    - phabricator-repos:/repos
    - phabricator-extensions:/srv/phabricator/phabricator/src/extensions
    depends_on:
    - mariadb
    links:
    - mariadb
    environment:
    - MYSQL_HOST=mariadb
    - MYSQL_USER
    - MYSQL_PASS
    - PHABRICATOR_REPOSITORY_PATH=/repos
    - PHABRICATOR_HOST="phabricator.flowercluster.io:8080"
    image: flowercluster/phabricator
  mariadb:
    restart: always
    volumes:
    - phabricator-mysql:/var/lib/mysql
    image: mariadb:10.3
    environment:
    - MYSQL_ROOT_PASSWORD

volumes:
  phabricator-mysql:
    driver: local
  phabricator-repos:
    driver: local
  phabricator-extensions:
    driver: local
