version: '2'
services:
  phabricator:
    restart: always
    ports:
     - "62443:443"
     - "62080:80"
     - "62022:2222"
    volumes:
     - phabricator-repos:/repos
     - phabricator-extensions:/srv/phabricator/phabricator/src/extensions
    depends_on:
     - mysql
    links:
     - mysql
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - PHABRICATOR_REPOSITORY_PATH=/repos
     - PHABRICATOR_HOST=phabricator.flowercluster.io
    image: flowercluster/phabricator
  mysql:
    restart: always
    volumes:
     - phabricator-mysql:/var/lib/mysql
    image: mysql:5.7.14
    environment:
     - MYSQL_ROOT_PASSWORD

volumes:
  phabricator-mysql:
    driver: local
  phabricator-repos:
    driver: local
  phabricator-extensions:
    driver: local
